//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sa11ytaire4All {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class StringResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StringResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Sa11ytaire4All.StringResources", typeof(StringResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One.
        /// </summary>
        internal static string _1 {
            get {
                return ResourceManager.GetString("1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10.
        /// </summary>
        internal static string _10 {
            get {
                return ResourceManager.GetString("10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.
        /// </summary>
        internal static string _2 {
            get {
                return ResourceManager.GetString("2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.
        /// </summary>
        internal static string _3 {
            get {
                return ResourceManager.GetString("3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.
        /// </summary>
        internal static string _4 {
            get {
                return ResourceManager.GetString("4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.
        /// </summary>
        internal static string _5 {
            get {
                return ResourceManager.GetString("5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.
        /// </summary>
        internal static string _6 {
            get {
                return ResourceManager.GetString("6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 7.
        /// </summary>
        internal static string _7 {
            get {
                return ResourceManager.GetString("7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8.
        /// </summary>
        internal static string _8 {
            get {
                return ResourceManager.GetString("8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 9.
        /// </summary>
        internal static string _9 {
            get {
                return ResourceManager.GetString("9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessible Solitaire V1.31.
        /// </summary>
        internal static string AccessibleSolitaireVersion {
            get {
                return ResourceManager.GetString("AccessibleSolitaireVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubs pile:.
        /// </summary>
        internal static string AccessKeyClubsPileLabel_Text {
            get {
                return ResourceManager.GetString("AccessKeyClubsPileLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 1:.
        /// </summary>
        internal static string AccessKeyDealtCardPile1Label_Text {
            get {
                return ResourceManager.GetString("AccessKeyDealtCardPile1Label.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 2:.
        /// </summary>
        internal static string AccessKeyDealtCardPile2Label_Text {
            get {
                return ResourceManager.GetString("AccessKeyDealtCardPile2Label.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 3:.
        /// </summary>
        internal static string AccessKeyDealtCardPile3Label_Text {
            get {
                return ResourceManager.GetString("AccessKeyDealtCardPile3Label.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 4:.
        /// </summary>
        internal static string AccessKeyDealtCardPile4Label_Text {
            get {
                return ResourceManager.GetString("AccessKeyDealtCardPile4Label.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 5:.
        /// </summary>
        internal static string AccessKeyDealtCardPile5Label_Text {
            get {
                return ResourceManager.GetString("AccessKeyDealtCardPile5Label.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 6:.
        /// </summary>
        internal static string AccessKeyDealtCardPile6Label_Text {
            get {
                return ResourceManager.GetString("AccessKeyDealtCardPile6Label.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 7:.
        /// </summary>
        internal static string AccessKeyDealtCardPile7Label_Text {
            get {
                return ResourceManager.GetString("AccessKeyDealtCardPile7Label.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamonds pile:.
        /// </summary>
        internal static string AccessKeyDiamondsPileLabel_Text {
            get {
                return ResourceManager.GetString("AccessKeyDiamondsPileLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearts pile:.
        /// </summary>
        internal static string AccessKeyHeartsPileLabel_Text {
            get {
                return ResourceManager.GetString("AccessKeyHeartsPileLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next card:.
        /// </summary>
        internal static string AccessKeyNextCardLabel_Text {
            get {
                return ResourceManager.GetString("AccessKeyNextCardLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spades pile:.
        /// </summary>
        internal static string AccessKeySpadesPileLabel_Text {
            get {
                return ResourceManager.GetString("AccessKeySpadesPileLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upturned card:.
        /// </summary>
        internal static string AccessKeyUpturnedCardLabel_Text {
            get {
                return ResourceManager.GetString("AccessKeyUpturnedCardLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ace.
        /// </summary>
        internal static string Ace {
            get {
                return ResourceManager.GetString("Ace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealt card selection.
        /// </summary>
        internal static string AllowSelectionByFaceDownCard {
            get {
                return ResourceManager.GetString("AllowSelectionByFaceDownCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight selected card set:.
        /// </summary>
        internal static string AllowSelectionByFaceDownCardButtonLabel {
            get {
                return ResourceManager.GetString("AllowSelectionByFaceDownCardButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select via face-down card:.
        /// </summary>
        internal static string AllowSelectionByFaceDownCardCheckboxLabel {
            get {
                return ResourceManager.GetString("AllowSelectionByFaceDownCardCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this option if you&apos;d like to tap any face-down card in a dealt card pile to select the nearest face-up card in the same pile..
        /// </summary>
        internal static string AllowSelectionByFaceDownCardInstructions {
            get {
                return ResourceManager.GetString("AllowSelectionByFaceDownCardInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All upturned cards turned back.
        /// </summary>
        internal static string AllUpturnedCardsTurnedBack {
            get {
                return ResourceManager.GetString("AllUpturnedCardsTurnedBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen reader announce game state.
        /// </summary>
        internal static string AnnouceState {
            get {
                return ResourceManager.GetString("AnnouceState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to can be moved to dealt card pile.
        /// </summary>
        internal static string CanBeMovedToDealtCardPile {
            get {
                return ResourceManager.GetString("CanBeMovedToDealtCardPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton_Content {
            get {
                return ResourceManager.GetString("CancelButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card.
        /// </summary>
        internal static string Card {
            get {
                return ResourceManager.GetString("Card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card Appearence.
        /// </summary>
        internal static string CardAppearence {
            get {
                return ResourceManager.GetString("CardAppearence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top-most upturned card.
        /// </summary>
        internal static string CardDeckUpturned_AutomationProperties_HelpText {
            get {
                return ResourceManager.GetString("CardDeckUpturned.AutomationProperties.HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Second from top upturned card.
        /// </summary>
        internal static string CardDeckUpturnedObscuredHigher_AutomationProperties_HelpText {
            get {
                return ResourceManager.GetString("CardDeckUpturnedObscuredHigher.AutomationProperties.HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Third from top upturned card.
        /// </summary>
        internal static string CardDeckUpturnedObscuredLower_AutomationProperties_HelpText {
            get {
                return ResourceManager.GetString("CardDeckUpturnedObscuredLower.AutomationProperties.HelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 1.
        /// </summary>
        internal static string CardPile1 {
            get {
                return ResourceManager.GetString("CardPile1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 2.
        /// </summary>
        internal static string CardPile2 {
            get {
                return ResourceManager.GetString("CardPile2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 3.
        /// </summary>
        internal static string CardPile3 {
            get {
                return ResourceManager.GetString("CardPile3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 4.
        /// </summary>
        internal static string CardPile4 {
            get {
                return ResourceManager.GetString("CardPile4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 5.
        /// </summary>
        internal static string CardPile5 {
            get {
                return ResourceManager.GetString("CardPile5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 6.
        /// </summary>
        internal static string CardPile6 {
            get {
                return ResourceManager.GetString("CardPile6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile 7.
        /// </summary>
        internal static string CardPile7 {
            get {
                return ResourceManager.GetString("CardPile7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        internal static string Cards {
            get {
                return ResourceManager.GetString("Cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of cards turned up.
        /// </summary>
        internal static string CardTurnCount {
            get {
                return ResourceManager.GetString("CardTurnCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How many cards would you like to be turned up when the Next Card button is clicked?.
        /// </summary>
        internal static string CardTurnCountInstructions {
            get {
                return ResourceManager.GetString("CardTurnCountInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card turn up count:.
        /// </summary>
        internal static string CardTurnCountPicker {
            get {
                return ResourceManager.GetString("CardTurnCountPicker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubs.
        /// </summary>
        internal static string Clubs {
            get {
                return ResourceManager.GetString("Clubs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubs pile.
        /// </summary>
        internal static string ClubsPile {
            get {
                return ResourceManager.GetString("ClubsPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations.
        /// </summary>
        internal static string Congratulations {
            get {
                return ResourceManager.GetString("Congratulations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darker.
        /// </summary>
        internal static string Darker {
            get {
                return ResourceManager.GetString("Darker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealt card pile.
        /// </summary>
        internal static string DealtCardPile {
            get {
                return ResourceManager.GetString("DealtCardPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dealt card piles.
        /// </summary>
        internal static string DealtCardPiles {
            get {
                return ResourceManager.GetString("DealtCardPiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamonds.
        /// </summary>
        internal static string Diamonds {
            get {
                return ResourceManager.GetString("Diamonds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamonds pile.
        /// </summary>
        internal static string DiamondsPile {
            get {
                return ResourceManager.GetString("DiamondsPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty.
        /// </summary>
        internal static string Empty {
            get {
                return ResourceManager.GetString("Empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty card pile.
        /// </summary>
        internal static string EmptyCardPile {
            get {
                return ResourceManager.GetString("EmptyCardPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable automatic hints.
        /// </summary>
        internal static string EnableAutomaticHintsCheckBox_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("EnableAutomaticHintsCheckBox.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enable automatic hints.
        /// </summary>
        internal static string EnableAutomaticHintsCheckBox_Content {
            get {
                return ResourceManager.GetString("EnableAutomaticHintsCheckBox.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you&apos;ve won! Would you like to start a new game?.
        /// </summary>
        internal static string endOfGameDialog_Content {
            get {
                return ResourceManager.GetString("endOfGameDialog.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart game.
        /// </summary>
        internal static string endOfGameDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("endOfGameDialog.PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit game.
        /// </summary>
        internal static string endOfGameDialog_SecondaryButtonText {
            get {
                return ResourceManager.GetString("endOfGameDialog.SecondaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Game Over.
        /// </summary>
        internal static string endOfGameDialog_Title {
            get {
                return ResourceManager.GetString("endOfGameDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend dealt card hit target.
        /// </summary>
        internal static string ExtendDealtCardHitTarget {
            get {
                return ResourceManager.GetString("ExtendDealtCardHitTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extend hit target:.
        /// </summary>
        internal static string ExtendDealtCardHitTargetCheckboxLabel {
            get {
                return ResourceManager.GetString("ExtendDealtCardHitTargetCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This setting only applies using a portrait screen orientation. When checked, the hit target for each of the topmost dealt cards extends across the width of the screen. The hit target is represented by a solid colour, and the dealt card appears in the middle of the area. Extending the hit target area may make it quicker to find the topmost card in each pile when moving your finger over the screen while using a screen reader..
        /// </summary>
        internal static string ExtendDealtCardHitTargetInstructions {
            get {
                return ResourceManager.GetString("ExtendDealtCardHitTargetInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face-down.
        /// </summary>
        internal static string FaceDown {
            get {
                return ResourceManager.GetString("FaceDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face-down cards cannot be selected..
        /// </summary>
        internal static string FaceDownCardsCannotBeSelected {
            get {
                return ResourceManager.GetString("FaceDownCardsCannotBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Welcome to the Accessible Solitaire game!
        ///
        ///Please click the Menu button and review the Help content to learn how to get the best game-playing experiences for you..
        /// </summary>
        internal static string FirstRunMessage {
            get {
                return ResourceManager.GetString("FirstRunMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip layout horizontally.
        /// </summary>
        internal static string FlipGameLayoutHorizontally {
            get {
                return ResourceManager.GetString("FlipGameLayoutHorizontally", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this option to flip the position of everything in the game horizontally. This means the Next Card button will be near the top right corner of the game rather than near the top left corner..
        /// </summary>
        internal static string FlipGameLayoutHorizontallyInstructions {
            get {
                return ResourceManager.GetString("FlipGameLayoutHorizontallyInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flip layout:.
        /// </summary>
        internal static string FlipGameLayoutHorizontallySwitchLabel {
            get {
                return ResourceManager.GetString("FlipGameLayoutHorizontallySwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The game has restarted..
        /// </summary>
        internal static string GameRestarted {
            get {
                return ResourceManager.GetString("GameRestarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearts.
        /// </summary>
        internal static string Hearts {
            get {
                return ResourceManager.GetString("Hearts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearts pile.
        /// </summary>
        internal static string HeartsPile {
            get {
                return ResourceManager.GetString("HeartsPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessible Solitaire Help.
        /// </summary>
        internal static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected cards highlight.
        /// </summary>
        internal static string HighlightSelectedCardSet {
            get {
                return ResourceManager.GetString("HighlightSelectedCardSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this option it you&apos;d like to highlight all cards that will be moved from a dealt card pile when a card is selected in that pile..
        /// </summary>
        internal static string HighlightSelectedCardSetInstructions {
            get {
                return ResourceManager.GetString("HighlightSelectedCardSetInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Highlight selected card set:.
        /// </summary>
        internal static string HighlightSelectedCardSetSwitchLabel {
            get {
                return ResourceManager.GetString("HighlightSelectedCardSetSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consider moving the.
        /// </summary>
        internal static string HowAboutMoving {
            get {
                return ResourceManager.GetString("HowAboutMoving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to How about turning over the next card?.
        /// </summary>
        internal static string HowAboutTurningOverCards {
            get {
                return ResourceManager.GetString("HowAboutTurningOverCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in dealt card pile.
        /// </summary>
        internal static string InDealtCardPile {
            get {
                return ResourceManager.GetString("InDealtCardPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to in selected set.
        /// </summary>
        internal static string InSelectedSet {
            get {
                return ResourceManager.GetString("InSelectedSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jack.
        /// </summary>
        internal static string Jack {
            get {
                return ResourceManager.GetString("Jack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to King.
        /// </summary>
        internal static string King {
            get {
                return ResourceManager.GetString("King", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Empty Dealt Card Pile.
        /// </summary>
        internal static string KingsOnlyToEmptyPile {
            get {
                return ResourceManager.GetString("KingsOnlyToEmptyPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Any card can be moved to an empty dealt card pile. If you&apos;d prefer that only Kings can be moved to the empty card pile, select this option..
        /// </summary>
        internal static string KingsOnlyToEmptyPileInstructions {
            get {
                return ResourceManager.GetString("KingsOnlyToEmptyPileInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Kings to empty card piles:.
        /// </summary>
        internal static string KingsOnlyToEmptyPileSwitchName {
            get {
                return ResourceManager.GetString("KingsOnlyToEmptyPileSwitchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launch help.
        /// </summary>
        internal static string LaunchHelpButton_Content {
            get {
                return ResourceManager.GetString("LaunchHelpButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lighter.
        /// </summary>
        internal static string Lighter {
            get {
                return ResourceManager.GetString("Lighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press and hold on card to zoom.
        /// </summary>
        internal static string LongPressOnCard {
            get {
                return ResourceManager.GetString("LongPressOnCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press and hold on a card for the card to fill the screen. Select the number of seconds required to press and hold on the card, or select &quot;Never&quot; to turn off the press and hold..
        /// </summary>
        internal static string LongPressOnCardInstructions {
            get {
                return ResourceManager.GetString("LongPressOnCardInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seconds:.
        /// </summary>
        internal static string LongPressOnCardPickerName {
            get {
                return ResourceManager.GetString("LongPressOnCardPickerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string MapAccessKeysPrimaryButtonText {
            get {
                return ResourceManager.GetString("MapAccessKeysPrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string MapAccessKeysSecondaryButtonText {
            get {
                return ResourceManager.GetString("MapAccessKeysSecondaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set access keys to use in Sa11ytaire.
        /// </summary>
        internal static string MapAccessKeysTitle {
            get {
                return ResourceManager.GetString("MapAccessKeysTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string Menu {
            get {
                return ResourceManager.GetString("Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face-down cards.
        /// </summary>
        internal static string MergeFaceDownCards {
            get {
                return ResourceManager.GetString("MergeFaceDownCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this option if you&apos;d like all face-down cards in each dealt card pile to be merged into a single item that shows the count of face-down cards in the pile..
        /// </summary>
        internal static string MergeFaceDownCardsInstructions {
            get {
                return ResourceManager.GetString("MergeFaceDownCardsInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merge face-down cards:.
        /// </summary>
        internal static string MergeFaceDownCardsSwitchLabel {
            get {
                return ResourceManager.GetString("MergeFaceDownCardsSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hmm, there might not be any available moves now..
        /// </summary>
        internal static string MightBeOutOfLuck {
            get {
                return ResourceManager.GetString("MightBeOutOfLuck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to More cards are available to turn over.
        /// </summary>
        internal static string MoreCardsAreAvailable {
            get {
                return ResourceManager.GetString("MoreCardsAreAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most recent notification.
        /// </summary>
        internal static string MostRecentNotificationTextBox_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("MostRecentNotificationTextBox.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moved.
        /// </summary>
        internal static string Moved {
            get {
                return ResourceManager.GetString("Moved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile of remaining cards, face down..
        /// </summary>
        internal static string NextCardPile_AutomationProperties_FullDescription {
            get {
                return ResourceManager.GetString("NextCardPile.AutomationProperties.FullDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next card.
        /// </summary>
        internal static string NextCardPile_NextCard {
            get {
                return ResourceManager.GetString("NextCardPile_NextCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn over cards.
        /// </summary>
        internal static string NextCardPile_TurnOverCards {
            get {
                return ResourceManager.GetString("NextCardPile_TurnOverCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No card.
        /// </summary>
        internal static string NoCard {
            get {
                return ResourceManager.GetString("NoCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No cards left in remaining cards pile.
        /// </summary>
        internal static string NoCardLeft {
            get {
                return ResourceManager.GetString("NoCardLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No move is available..
        /// </summary>
        internal static string NoMoveIsAvailable {
            get {
                return ResourceManager.GetString("NoMoveIsAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This card is not at the top of the upturned card pile, and cannot be selected..
        /// </summary>
        internal static string ObscuredUpturnedCardCannotBeSelected {
            get {
                return ResourceManager.GetString("ObscuredUpturnedCardCannotBeSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        internal static string Of {
            get {
                return ResourceManager.GetString("Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to off.
        /// </summary>
        internal static string Off {
            get {
                return ResourceManager.GetString("Off", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on.
        /// </summary>
        internal static string On {
            get {
                return ResourceManager.GetString("On", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to on top.
        /// </summary>
        internal static string OnTop {
            get {
                return ResourceManager.GetString("OnTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pile.
        /// </summary>
        internal static string Pile {
            get {
                return ResourceManager.GetString("Pile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign in.
        /// </summary>
        internal static string PlayerSignIn_Content {
            get {
                return ResourceManager.GetString("PlayerSignIn.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sound effects.
        /// </summary>
        internal static string PlaySoundEffectsCheckBox_Content {
            get {
                return ResourceManager.GetString("PlaySoundEffectsCheckBox.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play other sounds including when dealing cards or turning over the next cards..
        /// </summary>
        internal static string PlaySoundOther {
            get {
                return ResourceManager.GetString("PlaySoundOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other sounds:.
        /// </summary>
        internal static string PlaySoundOtherSwitchLabel {
            get {
                return ResourceManager.GetString("PlaySoundOtherSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a sound when a card move attempt is successful..
        /// </summary>
        internal static string PlaySoundSuccessfulMove {
            get {
                return ResourceManager.GetString("PlaySoundSuccessfulMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful sound:.
        /// </summary>
        internal static string PlaySoundSuccessfulMoveSwitchLabel {
            get {
                return ResourceManager.GetString("PlaySoundSuccessfulMoveSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play a sound when a card move attempt is unsuccessful..
        /// </summary>
        internal static string PlaySoundUnsuccessfulMove {
            get {
                return ResourceManager.GetString("PlaySoundUnsuccessfulMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful sound:.
        /// </summary>
        internal static string PlaySoundUnsuccessfulMoveSwitchLabel {
            get {
                return ResourceManager.GetString("PlaySoundUnsuccessfulMoveSwitchLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification audio.
        /// </summary>
        internal static string PlayTTSNotificationsCheckBox_Content {
            get {
                return ResourceManager.GetString("PlayTTSNotificationsCheckBox.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Popup.
        /// </summary>
        internal static string Popup {
            get {
                return ResourceManager.GetString("Popup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queen.
        /// </summary>
        internal static string Queen {
            get {
                return ResourceManager.GetString("Queen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        internal static string queryDialog_CloseButtonText {
            get {
                return ResourceManager.GetString("queryDialog.CloseButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string queryDialog_PrimaryButtonText {
            get {
                return ResourceManager.GetString("queryDialog.PrimaryButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart game.
        /// </summary>
        internal static string queryDialog_Title {
            get {
                return ResourceManager.GetString("queryDialog.Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to restart the game?.
        /// </summary>
        internal static string QueryRestartGame {
            get {
                return ResourceManager.GetString("QueryRestartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Congratulations, you&apos;ve won! Would you like to start a new game?.
        /// </summary>
        internal static string QueryRestartWonGame {
            get {
                return ResourceManager.GetString("QueryRestartWonGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Speech recognized:.
        /// </summary>
        internal static string RecognizedStatusLabel {
            get {
                return ResourceManager.GetString("RecognizedStatusLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restart Game.
        /// </summary>
        internal static string RestartGame {
            get {
                return ResourceManager.GetString("RestartGame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to R.
        /// </summary>
        internal static string RestoreDefaultsButton_AccessKey {
            get {
                return ResourceManager.GetString("RestoreDefaultsButton.AccessKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Restore defaults.
        /// </summary>
        internal static string RestoreDefaultsButton_Content {
            get {
                return ResourceManager.GetString("RestoreDefaultsButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to revealed.
        /// </summary>
        internal static string Revealed {
            get {
                return ResourceManager.GetString("Revealed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessible Solitaire.
        /// </summary>
        internal static string Sa11ytaire {
            get {
                return ResourceManager.GetString("Sa11ytaire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select card without Alt key.
        /// </summary>
        internal static string SelectCardWithoutAltKeyCheckBox_Content {
            get {
                return ResourceManager.GetString("SelectCardWithoutAltKeyCheckBox.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to selected.
        /// </summary>
        internal static string Selected {
            get {
                return ResourceManager.GetString("Selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select card without Alt key..
        /// </summary>
        internal static string SelectWithoutAltKey_Text {
            get {
                return ResourceManager.GetString("SelectWithoutAltKey.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set access key mapping.
        /// </summary>
        internal static string SetAccessKeyMapping_Content {
            get {
                return ResourceManager.GetString("SetAccessKeyMapping.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set.
        /// </summary>
        internal static string SetButton_Content {
            get {
                return ResourceManager.GetString("SetButton.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accessible Solitaire Settings.
        /// </summary>
        internal static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat with Sa11y.
        /// </summary>
        internal static string ShowBotCheckBoxLabel_Text {
            get {
                return ResourceManager.GetString("ShowBotCheckBoxLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show most recent notification.
        /// </summary>
        internal static string ShowNotificationWindowCheckBox_Content {
            get {
                return ResourceManager.GetString("ShowNotificationWindowCheckBox.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Card rank and suit display.
        /// </summary>
        internal static string ShowRankSuitLarge {
            get {
                return ResourceManager.GetString("ShowRankSuitLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check this option if you&apos;d like each card to show a large suit symbol and a large letter representing the card&apos;s rank..
        /// </summary>
        internal static string ShowRankSuitLargeInstructions {
            get {
                return ResourceManager.GetString("ShowRankSuitLargeInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show large rank and suit:.
        /// </summary>
        internal static string ShowRankSuitLargeSwitchName {
            get {
                return ResourceManager.GetString("ShowRankSuitLargeSwitchName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Screen Reader.
        /// </summary>
        internal static string ShowStateAnnouncementButton {
            get {
                return ResourceManager.GetString("ShowStateAnnouncementButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show state announcement button:.
        /// </summary>
        internal static string ShowStateAnnouncementButtonCheckboxLabel {
            get {
                return ResourceManager.GetString("ShowStateAnnouncementButtonCheckboxLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show a button to have a screen reader announce the state of the entire game..
        /// </summary>
        internal static string ShowStateAnnouncementButtonInstructions {
            get {
                return ResourceManager.GetString("ShowStateAnnouncementButtonInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Signing in....
        /// </summary>
        internal static string SigningIn {
            get {
                return ResourceManager.GetString("SigningIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single key to move card.
        /// </summary>
        internal static string SingleKeyToMoveCardCheckBox_Content {
            get {
                return ResourceManager.GetString("SingleKeyToMoveCardCheckBox.Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Single key to move card..
        /// </summary>
        internal static string SingleKeyToMoveTextBlock_Text {
            get {
                return ResourceManager.GetString("SingleKeyToMoveTextBlock.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sounds.
        /// </summary>
        internal static string Sounds {
            get {
                return ResourceManager.GetString("Sounds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spades.
        /// </summary>
        internal static string Spades {
            get {
                return ResourceManager.GetString("Spades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spades pile.
        /// </summary>
        internal static string SpadesPile {
            get {
                return ResourceManager.GetString("SpadesPile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suit Colours.
        /// </summary>
        internal static string SuitColours {
            get {
                return ResourceManager.GetString("SuitColours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clubs:.
        /// </summary>
        internal static string SuitColoursClubsPickerLabel {
            get {
                return ResourceManager.GetString("SuitColoursClubsPickerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diamonds:.
        /// </summary>
        internal static string SuitColoursDiamondsPickerLabel {
            get {
                return ResourceManager.GetString("SuitColoursDiamondsPickerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hearts:.
        /// </summary>
        internal static string SuitColoursHeartsPickerLabel {
            get {
                return ResourceManager.GetString("SuitColoursHeartsPickerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you&apos;d prefer to have cards show colours other than the traditional black and red for the four suits, select your preferred colours here..
        /// </summary>
        internal static string SuitColoursInstructions {
            get {
                return ResourceManager.GetString("SuitColoursInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spades:.
        /// </summary>
        internal static string SuitColoursSpadesPickerLabel {
            get {
                return ResourceManager.GetString("SuitColoursSpadesPickerLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch control is now.
        /// </summary>
        internal static string SwitchControl {
            get {
                return ResourceManager.GetString("SwitchControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch control on..
        /// </summary>
        internal static string SwitchControlOnTextBlock {
            get {
                return ResourceManager.GetString("SwitchControlOnTextBlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Switch control highlight speed:.
        /// </summary>
        internal static string SwitchScanSpeedLabel_Text {
            get {
                return ResourceManager.GetString("SwitchScanSpeedLabel.Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target card piles.
        /// </summary>
        internal static string TargetCardPiles {
            get {
                return ResourceManager.GetString("TargetCardPiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target piles.
        /// </summary>
        internal static string TargetPiles {
            get {
                return ResourceManager.GetString("TargetPiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to then.
        /// </summary>
        internal static string Then {
            get {
                return ResourceManager.GetString("Then", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There are no upturned cards shown.
        /// </summary>
        internal static string ThereAreNoUpturnedCards {
            get {
                return ResourceManager.GetString("ThereAreNoUpturnedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cards.
        /// </summary>
        internal static string TopCornerPilesLandmark_AutomationProperties_LocalizedLandmarkType {
            get {
                return ResourceManager.GetString("TopCornerPilesLandmark.AutomationProperties.LocalizedLandmarkType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remaining card piles.
        /// </summary>
        internal static string TopCornerPilesLandmark_AutomationProperties_Name {
            get {
                return ResourceManager.GetString("TopCornerPilesLandmark.AutomationProperties.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top upturned card is.
        /// </summary>
        internal static string TopUpturnedCardIs {
            get {
                return ResourceManager.GetString("TopUpturnedCardIs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to unselected.
        /// </summary>
        internal static string Unselected {
            get {
                return ResourceManager.GetString("Unselected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upturned.
        /// </summary>
        internal static string Upturned {
            get {
                return ResourceManager.GetString("Upturned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upturned Cards.
        /// </summary>
        internal static string UpturnedCards {
            get {
                return ResourceManager.GetString("UpturnedCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Listening....
        /// </summary>
        internal static string WaitingForSpeech {
            get {
                return ResourceManager.GetString("WaitingForSpeech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Increase the size of the entire game. The top area of the game will always occupy the top third of the screen, and can be scrolled in both directions. The lower part of the game containing all the dealt card piles can be scrolled separately..
        /// </summary>
        internal static string ZoomInstructions {
            get {
                return ResourceManager.GetString("ZoomInstructions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom Level.
        /// </summary>
        internal static string ZoomLevel {
            get {
                return ResourceManager.GetString("ZoomLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoom:.
        /// </summary>
        internal static string ZoomLevelPickerLevel {
            get {
                return ResourceManager.GetString("ZoomLevelPickerLevel", resourceCulture);
            }
        }
    }
}
